--- #YAML:1.0
name:               PDL-CCS
version:            1.18.1
abstract:           Sparse N-dimensional PDLs with compressed column storage
author:
    - Bryan Jurish
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    PDL:                2.4.2
    PDL::VectorValued:  0.06
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
